theme: jekyll-theme-cayman
title: Notify.lk Documentation
description: Start sending messages to your customers right away
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
